package main

const (
	WHITE_BUTTON_LED  byte = 13
	GREEN_BUTTON_LED  byte = 12
	YELLOW_BUTTON_LED byte = 11
	RED_BUTTON_LED    byte = 10
	SQUARE_BUTTON_LED byte = 9

	BLUE_LED       byte = 2
	GREEN_LED      byte = 3
	YELLOW_LED     byte = 4
	DUAL_LED_GREEN byte = 5
	RED_LED        byte = 6
	DUAL_LED_RED   byte = 7

	WHITE_BUTTON  byte = 30
	GREEN_BUTTON  byte = 32
	YELLOW_BUTTON byte = 34
	RED_BUTTON    byte = 36
	SQUARE_BUTTON byte = 38

	SWITCH_UP   byte = 25
	SWITCH_DOWN byte = 23
)

var LEDS = []byte{WHITE_BUTTON_LED, GREEN_BUTTON_LED, YELLOW_BUTTON_LED, RED_BUTTON_LED, SQUARE_BUTTON_LED, BLUE_LED, GREEN_LED,
	YELLOW_LED, DUAL_LED_GREEN, RED_LED, DUAL_LED_GREEN}

var BUTTONS = []byte{WHITE_BUTTON, GREEN_BUTTON, YELLOW_BUTTON, RED_BUTTON, SQUARE_BUTTON}

var BUTTON_LED_RELATIONS = map[byte]byte{
	WHITE_BUTTON:  WHITE_BUTTON_LED,
	GREEN_BUTTON:  GREEN_BUTTON_LED,
	YELLOW_BUTTON: YELLOW_BUTTON_LED,
	RED_BUTTON:    RED_BUTTON_LED,
	SQUARE_BUTTON: SQUARE_BUTTON_LED}
